# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' LidarIndexR -- Read the header for a local LAS/LAZ file
#'
#' Read the header information for a LAS/LAZ file including CRS information.
#' Only the file header is read (including VLRs) so you don't have to worry 
#' about the size of the LAS/LAZ file. This function is implemented in C++
#' and is 2+ orders of magnitude faster than \code{ReadLocalLASHeader()}.
#'
#' @param path Path for a LAS/LAZ file.
#' @return A data frame containing the CRS WKT information string and
#'   header info. If file has no CRS information, the crs column in the data frame
#'   will be an empty string.
#' @examples
#' \dontrun{
#' ReadLocalLASHeader()
#' }
#' @export
ReadLASHeader <- function(path) {
    .Call(`_LidarIndexR_ReadLASHeader`, path)
}

